WITH users AS (
    SELECT *
    FROM {{ref('trans__user_status')}}
)

,add_history_columns AS (
    SELECT
        *
        ,MAX(case when event = 'REFRESH' then EVENT_DATE_TIME end) OVER (PARTITION BY USER_ID ORDER BY EVENT_DATE_TIME ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS LAST_REFRESH_EVENT
        ,MAX(case when event = 'TRANSACT' then EVENT_DATE_TIME end) OVER (PARTITION BY USER_ID ORDER BY EVENT_DATE_TIME ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS LAST_TRANSACT_EVENT
    FROM
        users
)

SELECT *
FROM add_history_columns