WITH user_events AS (
    SELECT *
    FROM {{ref('trans__user_events')}}
)

,add_history_columns AS (
    SELECT
        *
        ,MAX(CASE WHEN EVENT = 'REFRESH' THEN EVENT_DATE_TIME END)
            OVER (PARTITION BY USER_ID ORDER BY EVENT_DATE_TIME ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS LAST_REFRESH_EVENT
        ,MAX(CASE WHEN EVENT = 'TRANSACT' THEN EVENT_DATE_TIME END)
            OVER (PARTITION BY USER_ID ORDER BY EVENT_DATE_TIME ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS LAST_TRANSACT_EVENT
        ,MIN(CASE WHEN EVENT = 'TRANSACT' THEN EVENT_DATE_TIME END)
            OVER (PARTITION BY USER_ID ORDER BY EVENT_DATE_TIME ROWS BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING) AS NEXT_TRANSACT_EVENT
    FROM
        user_events
)

SELECT *
FROM add_history_columns